language: generic
sudo: required 
services:
  - docker

before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"      
  - docker build -t test-react -f Dockerfile.dev .

script:
  - docker run -e CI=true test-react npm run test
